backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "produk"
    label: "Produk"
    folder: "_produk"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Deskripsi", name: "description", widget: "text" }
      - { label: "Harga", name: "price", widget: "string" }
      - { label: "Gambar", name: "image", widget: "image" }
